### ISSUE TITLE
`say` is not defined in Runfile

### ISSUE THREAD

**Issue by wolfgang42** [DannyBen/bashly#111]
I'm trying to run shellcheck, but getting an error:
```
$ bundle exec run shellcheck
Traceback (most recent call last):
        9: from /home/wolf/src/vend/bashly/vendor/bundle/ruby/2.7.0/bin/run:23:in `<main>'
        8: from /home/wolf/src/vend/bashly/vendor/bundle/ruby/2.7.0/bin/run:23:in `load'
        7: from /home/wolf/src/vend/bashly/vendor/bundle/ruby/2.7.0/gems/runfile-0.12.0/bin/run:10:in `<top (required)>'
        6: from /home/wolf/src/vend/bashly/vendor/bundle/ruby/2.7.0/gems/runfile-0.12.0/lib/runfile/runner.rb:47:in `execute'
        5: from /home/wolf/src/vend/bashly/vendor/bundle/ruby/2.7.0/gems/runfile-0.12.0/lib/runfile/runner.rb:102:in `run'
        4: from /home/wolf/src/vend/bashly/vendor/bundle/ruby/2.7.0/gems/runfile-0.12.0/lib/runfile/runner.rb:133:in `docopt_exec'
        3: from /home/wolf/src/vend/bashly/vendor/bundle/ruby/2.7.0/gems/runfile-0.12.0/lib/runfile/action.rb:18:in `execute'
        2: from Runfile:20:in `block in <top (required)>'
        1: from Runfile:20:in `each'
Runfile:23:in `block (2 levels) in <top (required)>': undefined method `say' for main:Object (NoMethodError)
```

Not sure where `say` is supposed to come from, I assume a library somewhere should be defining it?

**Comment by DannyBen** [comment]
Fixed in #112 - `say` comes from the Colsole gem which used to be bundled with the Runfile gem, but I removed it yesterday for [various reasons](https://github.com/DannyBen/runfile/releases/tag/v0.12.0).
