### ISSUE TITLE
Ambiguous error messages

### ISSUE THREAD

**Issue by taqtiqa-mark** [DannyBen/bashly#283]
```bash 
$ bashly generate
Psych::SyntaxError
(src/conf/build.yml): did not find expected key while parsing a block mapping at line 80 column 5
```

 That line is an import which appears no different from the surrounding imports.
 Any hints appreciated.

**Comment by taqtiqa-mark** [comment]
```bash
$ bashly validate
Psych::SyntaxError
(src/conf/build.yml): did not find expected key while parsing a block mapping at line 80 column 5
```

**Comment by taqtiqa-mark** [comment]
```bash 
$ bashly validate
/usr/bin/bashly:25:in `<main>'
/usr/bin/bashly:25:in `load'
/usr/lib/ruby/gems/3.1.0/gems/bashly-0.8.6/bin/bashly:9:in `<top (required)>'
/usr/lib/ruby/gems/3.1.0/gems/mister_bin-0.7.1/lib/mister_bin/runner.rb:36:in `run'
/usr/lib/ruby/gems/3.1.0/gems/mister_bin-0.7.1/lib/mister_bin/runner.rb:47:in `execute'
/usr/lib/ruby/gems/3.1.0/gems/mister_bin-0.7.1/lib/mister_bin/command.rb:19:in `execute'
/usr/lib/ruby/gems/3.1.0/gems/bashly-0.8.6/lib/bashly/commands/validate.rb:12:in `run'
/usr/lib/ruby/gems/3.1.0/gems/bashly-0.8.6/lib/bashly/commands/base.rb:18:in `validate_config'
/usr/lib/ruby/gems/3.1.0/gems/bashly-0.8.6/lib/bashly/commands/base.rb:14:in `config_validator'
/usr/lib/ruby/gems/3.1.0/gems/bashly-0.8.6/lib/bashly/commands/base.rb:10:in `config'
/usr/lib/ruby/gems/3.1.0/gems/bashly-0.8.6/lib/bashly/config.rb:13:in `new'
/usr/lib/ruby/gems/3.1.0/gems/bashly-0.8.6/lib/bashly/refinements/compose_refinements.rb:7:in `compose'
/usr/lib/ruby/gems/3.1.0/gems/bashly-0.8.6/lib/bashly/refinements/compose_refinements.rb:7:in `each'
/usr/lib/ruby/gems/3.1.0/gems/bashly-0.8.6/lib/bashly/refinements/compose_refinements.rb:16:in `block in compose'
/usr/lib/ruby/gems/3.1.0/gems/bashly-0.8.6/lib/bashly/refinements/compose_refinements.rb:36:in `compose'
/usr/lib/ruby/gems/3.1.0/gems/bashly-0.8.6/lib/bashly/refinements/compose_refinements.rb:36:in `map'
/usr/lib/ruby/gems/3.1.0/gems/bashly-0.8.6/lib/bashly/refinements/compose_refinements.rb:38:in `block in compose'
/usr/lib/ruby/gems/3.1.0/gems/bashly-0.8.6/lib/bashly/refinements/compose_refinements.rb:7:in `compose'
/usr/lib/ruby/gems/3.1.0/gems/bashly-0.8.6/lib/bashly/refinements/compose_refinements.rb:7:in `each'
/usr/lib/ruby/gems/3.1.0/gems/bashly-0.8.6/lib/bashly/refinements/compose_refinements.rb:16:in `block in compose'
/usr/lib/ruby/gems/3.1.0/gems/bashly-0.8.6/lib/bashly/refinements/compose_refinements.rb:36:in `compose'
/usr/lib/ruby/gems/3.1.0/gems/bashly-0.8.6/lib/bashly/refinements/compose_refinements.rb:36:in `map'
/usr/lib/ruby/gems/3.1.0/gems/bashly-0.8.6/lib/bashly/refinements/compose_refinements.rb:38:in `block in compose'
/usr/lib/ruby/gems/3.1.0/gems/bashly-0.8.6/lib/bashly/refinements/compose_refinements.rb:7:in `compose'
/usr/lib/ruby/gems/3.1.0/gems/bashly-0.8.6/lib/bashly/refinements/compose_refinements.rb:7:in `each'
/usr/lib/ruby/gems/3.1.0/gems/bashly-0.8.6/lib/bashly/refinements/compose_refinements.rb:9:in `block in compose'
/usr/lib/ruby/gems/3.1.0/gems/bashly-0.8.6/lib/bashly/refinements/compose_refinements.rb:25:in `safe_load_yaml'
/usr/lib/ruby/gems/3.1.0/gems/bashly-0.8.6/lib/bashly/extensions/yaml.rb:4:in `properly_load_file'
/usr/lib/ruby/3.1.0/psych.rb:670:in `load_file'
/usr/lib/ruby/3.1.0/psych.rb:670:in `open'
/usr/lib/ruby/3.1.0/psych.rb:671:in `block in load_file'
/usr/lib/ruby/3.1.0/psych.rb:370:in `load'
/usr/lib/ruby/3.1.0/psych.rb:324:in `safe_load'
/usr/lib/ruby/3.1.0/psych.rb:399:in `parse'
/usr/lib/ruby/3.1.0/psych.rb:455:in `parse_stream'
/usr/lib/ruby/3.1.0/psych.rb:455:in `parse'
Psych::SyntaxError
(src/conf/build.yml): did not find expected key while parsing a block mapping at line 80 column 5
```

**Comment by taqtiqa-mark** [comment]
If I duplicate line 79 import to line 80 the error still reports line 80 as the same problem.

**Comment by taqtiqa-mark** [comment]
Is it possible that line 80 refers to a different file? Even a temporary file?

**Comment by DannyBen** [comment]
This is an invalid YAML error. I cannot help without seeing the YAMLs.
This is [probably an indentation error](https://stackoverflow.com/questions/54965199/did-not-find-expected-key-while-parsing-a-block-mapping).

**Comment by taqtiqa-mark** [comment]
> This is an invalid YAML error.

Agreed. But what is invalid?
The vscode linter from Redhat says everything is good:
https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml

> This is [probably an indentation error](https://stackoverflow.com/questions/54965199/did-not-find-expected-key-while-parsing-a-block-mapping).

Maybe that could be a test case - to land on error logic that isolates the error?

**Comment by DannyBen** [comment]
> I cannot help without seeing the YAMLs.

**Comment by taqtiqa-mark** [comment]
there are a couple of 1000 lines....

**Comment by DannyBen** [comment]
Is you get a PsychError, this is outside of bashly's control. It means the YAML is not a valid YAML syntax, and the Ruby YAML library is incapable of reading it.

If you have a YAML file with over 2000 lines, you should split it using `import`.

You can also try to figure out what is wrong with your YAML in an online service such as http://www.yamllint.com/

Another debugging trick: delete half the file and try. If you still see and error, it is in the other half. Rinse and repeat.

There is literally nothing I can do from bashly's perspective. If the Psych error does not show you the exact file and line it fails on, I cannot do it as well.

**Comment by taqtiqa-mark** [comment]
> If you have a YAML file with over 2000 lines, you should split it using `import`.

Addressed above.



> You can also try to figure out what is wrong with your YAML in an online service such as

Addressed above.



> There is literally nothing I can do from bashly's perspective.

I'm more optimistic - just busy right now.
